[project]
name = "wudi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.0",
    "jinja2>=3.1.6",
    "uvicorn>=0.35.0",
]
