apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: pipelines-as-code
spec:
  description: |
    Clones a git repository.
  params:
    - name: url
      description: Repository URL to clone from.
      type: string
    - name: revision
      description: Revision to checkout.
      type: string
      default: "main"
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this Workspace.
  results:
    - name: commit
      description: The precise commit SHA that was fetched by this Task.
    - name: url
      description: The precise URL that was fetched by this Task.
  steps:
    - name: cleanup
      image: alpine:3.18
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo "Cleaning up workspace directory..."
        # a safe way to delete contents without deleting the directory itself
        find . -mindepth 1 -maxdepth 1 -exec rm -rf {} \;

    - name: clone
      image: alpine/git
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -ex
        git clone "$(params.url)" .
        git checkout "$(params.revision)"
        COMMIT_SHA=$(git rev-parse HEAD)
        echo -n "$COMMIT_SHA" > "$(results.commit.path)"
        echo -n "$(params.url)" > "$(results.url.path)"
