# Simplified Git Clone Task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: pipelines-as-code
spec:
  description: |
    Simple git clone task with minimal parameters

  params:
    - name: url
      description: Repository URL to clone from
      type: string
    - name: revision
      description: Revision to checkout
      type: string
      default: "main"

  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this Workspace

  results:
    - name: commit
      description: The precise commit SHA that was fetched by this Task
    - name: url
      description: The precise URL that was fetched by this Task

  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
      workingDir: $(workspaces.output.path)
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      env:
        - name: HOME
          value: /home/git
        - name: PARAM_URL
          value: $(params.url)
        - name: PARAM_REVISION
          value: $(params.revision)
        - name: WORKSPACE_OUTPUT_PATH
          value: $(workspaces.output.path)
      command: ['/ko-app/git-init']
      args:
        - "-url=$(params.url)"
        - "-revision=$(params.revision)"
        - "-path=$(workspaces.output.path)"
      volumeMounts:
        - name: home
          mountPath: /home/git
          subPath: git
        - name: home
          mountPath: /home/git/.ssh
          subPath: .ssh

  volumes:
    - name: home
      emptyDir: {}
