apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  description: Clone the code repository to the workspace.
  params:
    - name: url
      type: string
      description: git url to clone
      default: ""
    - name: revision
      type: string
      description: git branch to checkout
      default: "main"
  workspaces:
    - name: source
      description: The git repo will be cloned onto the volume backing this workspace
  results:
    - name: commit
      description: The git commit SHA
  steps:
    - name: git-clone
      image: uhub.service.ucloud.cn/xinxin-istio/git:v2.45.2
      script: |
        # The original git clone command is still here
        git clone -b $(params.revision) -v $(params.url) $(workspaces.source.path)/source

        # New commands to get the commit SHA
        cd $(workspaces.source.path)/source
        git rev-parse HEAD | tr -d '\n' | tee $(results.commit.path)
