# Simplified Kaniko Build Task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
  namespace: pipelines-as-code
spec:
  description: |
    Builds and pushes a container image using Kaniko.
  params:
    - name: dockerfile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: image-url
      description: Url of image repository
    - name: image-tag
      description: Tag to apply to the built image
      default: latest
  workspaces:
    - name: source
      description: Holds the context and Dockerfile
  steps:
    - name: debug-context
      workingDir: $(workspaces.source.path)
      image: uhub.service.ucloud.cn/base-images/alpine:latest
      script: |
        echo "=== Debug: Checking build context ==="
        echo "Working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "\n=== Dockerfile content ==="
        cat $(params.dockerfile) || echo "Dockerfile not found!"
        echo "\n=== Git status (if available) ==="
        git log --oneline -1 2>/dev/null || echo "Not a git repository"
        echo "=== End debug info ==="

    - name: build-and-push
      workingDir: $(workspaces.source.path)
      image: uhub.service.ucloud.cn/base-images/executor:v1.9.0
      runAfter:
        - debug-context
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.dockerfile)
        - --context=$(workspaces.source.path)
        - --destination=$(params.image-url):$(params.image-tag)
        - --cleanup
        - --reproducible
        - --cache=false
        - --no-push-cache
        - --no-cache
        - --force
        - --skip-tls-verify
        - --log-format=text
        - --verbosity=info
        - --build-arg=BUILDKIT_INLINE_CACHE=0
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 1000m
  volumes:
    - name: docker-config
      secret:
        secretName: docker-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
