# Simplified Kaniko Build Task
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build-simple
  namespace: pipelines-as-code
spec:
  description: |
    Simple kaniko build task without push

  params:
    - name: IMAGE
      description: Name of the image to build
      type: string
    - name: DOCKERFILE
      description: Path to the Dockerfile
      type: string
      default: "./Dockerfile"
    - name: CONTEXT
      description: The build context
      type: string
      default: "./"

  workspaces:
    - name: source
      description: Holds the context and Dockerfile

  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built
    - name: IMAGE_URL
      description: URL of the image just built

  steps:
    - name: build-and-push
      workingDir: $(workspaces.source.path)
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE)
        - --digest-file=$(results.IMAGE_DIGEST.path)
        - --no-push
        - --cache=false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "200m"