# Simplified CI Pipeline
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline-simple
  namespace: pipelines-as-code
spec:
  description: |
    Minimal CI pipeline with git clone and build

  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: git-revision
      type: string
      description: Git revision to checkout
      default: "main"
    - name: image-name
      type: string
      description: Container image name
      default: "uhub.service.ucloud.cn/base-images/wudi-app:latest"

  workspaces:
    - name: shared-data
      description: Shared workspace for source code

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone-simple
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    - name: build-and-push
      taskRef:
        name: kaniko-build-simple
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params.image-name)
        - name: DOCKERFILE
          value: "./Dockerfile"
        - name: CONTEXT
          value: "./"