# Optimized PipelineRun for resource-constrained environments
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-pipeline-run-optimized
  namespace: pipelines-as-code
  labels:
    app.kubernetes.io/name: ci-pipeline-run
    app.kubernetes.io/version: "1.0.0"
  annotations:
    tekton.dev/git-status: "true"
    tekton.dev/git-url: "https://github.com/your-org/your-repo"
spec:
  pipelineRef:
    name: ci-pipeline

  # Optimized parameters for smaller resource footprint
  params:
    - name: git-url
      value: "https://github.com/your-org/your-repo.git"
    - name: git-revision
      value: "main"
    - name: app-name
      value: "wudi-app"
    - name: app-version
      value: "v1.0.0"
    - name: image-registry
      value: "uhub.service.ucloud.cn/base-images"
    - name: image-repository
      value: "wudi-app"
    - name: image-tag
      value: "latest"
    - name: dockerfile-path
      value: "./Dockerfile"
    - name: context-path
      value: "."

  # Optimized workspaces with smaller storage requests
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi  # Reduced from default 5Gi
          storageClassName: standard  # Use appropriate storage class

    - name: docker-credentials
      secret:
        secretName: docker-registry-secret
        optional: true

    - name: git-credentials
      secret:
        secretName: git-credentials-secret
        optional: true

  # Resource-aware task run specifications
  taskRunSpecs:
    - pipelineTaskName: git-clone
      taskServiceAccountName: pipeline-sa
      computeResources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"

    - pipelineTaskName: build-and-push
      taskServiceAccountName: pipeline-sa
      computeResources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "1000m"

  timeouts:
    pipeline: "30m"
    tasks: "20m"
    finally: "5m"

  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      fsGroup: 65532
