# Improved PipelineRun with dynamic tagging
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: pipelines-as-code
  generateName: ci-pipeline-run-
  annotations:
    pipelinesascode.tekton.dev/on-comment: "/retest"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && source_branch.matches("feat/.*") && target_branch == "main"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/task-timeout: "10m"
    pipelinesascode.tekton.dev/pipeline-timeout: "15m"
spec:
  pipelineRef:
    name: ci-pipeline

  params:
    - name: git-url
      value: "https://github.com/xinxin20020807/wudi"
    - name: git-revision
      value: "main"
    - name: image-url
      value: "uhub.service.ucloud.cn/base-images/wudi-app"
    - name: image-tag
      value: "$(context.pipelineRun.name)-$(context.pipelineRun.uid[0:8])"

  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-ssd
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

  # Enhanced timeout settings
  timeouts:
    pipeline: "30m"
    tasks: "15m"
    finally: "5m"

  # Enhanced security and resource settings
  podTemplate:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      fsGroup: 0
    nodeSelector:
      kubernetes.io/arch: amd64
    tolerations:
      - key: "node-role.kubernetes.io/ci"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: "node-type"
                  operator: In
                  values: ["ci-optimized"]
