# CI Pipeline
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: pipelines-as-code
spec:
  description: |
    Minimal CI pipeline with git clone and build

  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: git-revision
      type: string
      description: Git revision to checkout
      default: "main"
    - name: image-url
      type: string
      description: Container image repository URL
    - name: image-tag
      type: string
      description: Container image tag
      default: latest

  workspaces:
    - name: shared-data
      description: Shared workspace for source code

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)

    - name: build-and-push
      taskRef:
        name: kaniko-build
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: image-url
          value: $(params.image-url)
        - name: image-tag
          value: $(params.image-tag)
