# PipelineRun
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: pipelines-as-code
  generateName: ci-pipeline-run-
  annotations:
    pipelinesascode.tekton.dev/on-comment: "/retest"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && source_branch.matches("feat/.*") && target_branch == "main"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/task-timeout: "10m"
    pipelinesascode.tekton.dev/pipeline-timeout: "15m"
spec:
  pipelineRef:
    name: ci-pipeline

  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: git-revision
      value: "{{revision}}"
    - name: image-url
      value: "uhub.service.ucloud.cn/base-images/wudi-app"
    - name: image-tag
      value: "{{short_sha}}"

  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-ssd
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

  # 简化的超时设置
  timeouts:
    pipeline: "10m"
    tasks: "5m"

  # 简化的安全上下文
  podTemplate:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
