# PipelineRun with PVC for data persistence between tasks
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ci-pipeline-run-
  namespace: pipelines-as-code
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, master, develop, feat/*]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/task-timeout: "15m"
    pipelinesascode.tekton.dev/pipeline-timeout: "30m"
spec:
  pipelineRef:
    name: ci-pipeline
  params:
    - name: git-url
      value: "{{repo_url}}" # Use placeholder for repo URL
    - name: git-revision
      value: "{{revision}}" # This will be the PR's head commit SHA
    - name: image-url
      value: "uhub.service.ucloud.cn/wudi1111/wudi"
    - name: image-tag
      value: "pr-{{pull_request_number}}" # This will be the PR's source branch name

  # Use PVC for persistent data sharing between tasks#
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        metadata:
          generateName: "workspace-"
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: "ebs-ssd"  # 根据你的集群调整
          resources:
            requests:
              storage: 10Gi

  # Timeout settings
  timeouts:
    pipeline: "30m"
    tasks: "15m"

  # Pod template with security and resource settings
  podTemplate:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      fsGroup: 0
    # Resource limits
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
        ephemeral-storage: "5Gi"
      limits:
        memory: "512Mi"
        cpu: "1000m"
        ephemeral-storage: "10Gi"
    # Node selection for better performance
    nodeSelector:
      kubernetes.io/arch: amd64
    # Tolerations for dedicated nodes
    tolerations:
      - key: "tekton"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    # Affinity for better scheduling
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: "node-type"
                  operator: In
                  values: ["compute"]
