# PipelineRun
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: pipelines-as-code
  generateName: ci-pipeline-run-
  annotations:
    # Pipelines as Code annotations for GitHub integration
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, master]"
    pipelinesascode.tekton.dev/on-source-branch: "[main, master, feature/*]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/task-timeout: "10m"
    pipelinesascode.tekton.dev/pipeline-timeout: "15m"
spec:
  pipelineRef:
    name: ci-pipeline

  params:
    - name: git-url
      value: "https://github.com/xinxin20020807/wudi"
    - name: git-revision
      value: "main"
    - name: image-name
      value: "uhub.service.ucloud.cn/base-images/wudi-app:latest"

  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: tekton-workspace-pvc

  # 简化的超时设置
  timeouts:
    pipeline: "10m"
    tasks: "5m"

  # 使用默认服务账户
  serviceAccountName: default

  # 简化的安全上下文
  podTemplate:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
