# PipelineRun
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-pipeline-run
  namespace: pipelines-as-code
  generateName: ci-pipeline-run-
spec:
  pipelineRef:
    name: ci-pipeline

  params:
    - name: git-url
      value: "https://github.com/xinxin20020807/wudi"
    - name: git-revision
      value: "main"
    - name: image-name
      value: "uhub.service.ucloud.cn/base-images/wudi-app:latest"

  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

  # 简化的超时设置
  timeouts:
    pipeline: "10m"
    tasks: "5m"

  # 使用默认服务账户
  serviceAccountName: default

  # 简化的安全上下文
  podTemplate:
    securityContext:
      runAsNonRoot: false
      runAsUser: 0