# PersistentVolumeClaim for Tekton Workspace
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-workspace-pvc
  namespace: pipelines-as-code
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-ssd
  resources:
    requests:
      storage: 1Gi