# ServiceAccount for Tekton Pipeline
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
  namespace: pipelines-as-code
  labels:
    app.kubernetes.io/name: pipeline-sa
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: tekton-pipelines
  annotations:
    description: "ServiceAccount for running Tekton pipelines with necessary permissions"

---
# ClusterRole with necessary permissions for pipeline execution
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-sa-clusterrole
  labels:
    app.kubernetes.io/name: pipeline-sa-clusterrole
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: tekton-pipelines
rules:
  # Permissions for managing pods (required for TaskRuns)
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
  
  # Permissions for managing persistent volume claims
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
  
  # Permissions for managing config maps and secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  
  # Permissions for managing services and endpoints
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  
  # Permissions for Tekton resources
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "taskruns", "pipelines", "pipelineruns"]
    verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
  
  # Permissions for managing events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  
  # Permissions for managing deployments and other workloads
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  
  # Permissions for managing ingress
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding to bind the ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-sa-clusterrolebinding
  labels:
    app.kubernetes.io/name: pipeline-sa-clusterrolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: pipelines-as-code
roleRef:
  kind: ClusterRole
  name: pipeline-sa-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
# Additional RoleBinding for namespace-specific permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-sa-rolebinding
  namespace: pipelines-as-code
  labels:
    app.kubernetes.io/name: pipeline-sa-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: pipeline-sa
    namespace: pipelines-as-code
roleRef:
  kind: ClusterRole
  name: edit  # Use built-in edit role for namespace operations
  apiGroup: rbac.authorization.k8s.io